version: "3"

services:
  ansible-base:
    image: ansible/centos7-ansible
    # Give More Resources To Docker Container If Needed:
    # https://www.baeldung.com/ops/docker-memory-limit
    mem_limit: 2G
    mem_reservation: 1G
    cpus: 2.00
    container_name: ansible-base
    tty: true
    cap_add:
      - ALL
    privileged: true
    volumes:
      - ./volumes/ansible-base/opt-splunk-etc:/opt/splunk/etc
      - ./volumes/ansible-base/opt-splunk-var:/opt/splunk/var
      - ./volumes/ansible-base:/volumes/ansible-base
      - ./volumes/all:/volumes/all
      - ./volumes/user2:/volumes/user2
      - ./volumes/user3:/volumes/user3
      - ./volumes/user4:/volumes/user4
    # environment:
    #   - SPLUNK_HOME=/opt/splunk/
    network_mode: host
    # This link was used to figure out what flags would automate the installation and first RUN process for admin account creation.
    # https://docs.splunk.com/Documentation/Splunk/latest/Security/Secureyouradminaccount#Create_admin_credentials_using_the_--seed-passwd_or_--gen-and-print-passwd_CLI_arguments
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        rm -rf /volumes/ansible-base/opt-splunk-etc/*
        rm -rf /volumes/ansible-base/opt-splunk-var/*
        yum install epel-release -y
        rpm -i /volumes/ansible-base/splunk-*.rpm
        /opt/splunk/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd iLoveNewYork11230
        /bin/bash

  User2:
    image: mcnaughton/centos-base
    container_name: user2-10.9.0.2
    stdin_open: true
    hostname: user2
    volumes:
      - ./volumes/user2:/volumes/user2
      - ./volumes/all:/volumes/all
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.2
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        yum install epel-release -y
        rpm -i /volumes/all/splunkforwarder-*.rpm
        echo [*] Waiting for 10 Seconds Before Copying Config File.
        sleep 12
        cp -r /volumes/all/user-seed.conf /opt/splunkforwarder/etc/system/local/
        echo [*] Copying Completed Now Setting Up Splunk Forwarder.
        /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd iLoveNewYork11230
        /opt/splunkforwarder/bin/splunk add forward-server cyberarmor-base:11000 -auth admin:iLoveNewYork11230
        /opt/splunkforwarder/bin/splunk add monitor /var/log/
        /opt/splunkforwarder/bin/splunk status
        /bin/bash


  User3:
    image: mcnaughton/centos-base
    container_name: user3-10.9.0.3
    stdin_open: true
    hostname: user3
    cap_add:
      - ALL
    volumes:
      - ./volumes/user3:/volumes/user3
      - ./volumes/all:/volumes/all
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.3
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        yum install epel-release -y
        rpm -i /volumes/all/splunkforwarder-*.rpm
        echo [*] Waiting for 10 Seconds Before Copying Config File.
        sleep 12
        cp -r /volumes/all/user-seed.conf /opt/splunkforwarder/etc/system/local/
        echo [*] Copying Completed Now Setting Up Splunk Forwarder.
        /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd iLoveNewYork11230
        /opt/splunkforwarder/bin/splunk add forward-server cyberarmor-base:11000 -auth admin:iLoveNewYork11230
        /opt/splunkforwarder/bin/splunk add monitor /var/log/
        /opt/splunkforwarder/bin/splunk status
        /bin/bash


  User4:
    image: mcnaughton/centos-base
    container_name: user4-10.9.0.4
    stdin_open: true
    hostname: user4
    cap_add:
      - ALL
    volumes:
      - ./volumes/user4:/volumes/user4
      - ./volumes/all:/volumes/all
    networks:
      net-10.9.0.0:
        ipv4_address: 10.9.0.4
    entrypoint: ["/bin/sh","-c"]
    command:
      - |
        yum install epel-release -y
        rpm -i /volumes/all/splunkforwarder-*.rpm
        echo [*] Waiting for 10 Seconds Before Copying Config File.
        sleep 12
        cp -r /volumes/all/user-seed.conf /opt/splunkforwarder/etc/system/local/
        echo [*] Copying Completed Now Setting Up Splunk Forwarder.
        /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt --seed-passwd iLoveNewYork11230
        /opt/splunkforwarder/bin/splunk add forward-server cyberarmor-base:11000 -auth admin:iLoveNewYork11230
        /opt/splunkforwarder/bin/splunk add monitor /var/log/
        /opt/splunkforwarder/bin/splunk status
        /bin/bash


networks:
  net-10.9.0.0:
    name: net-10.9.0.0
    ipam:
      config:
        - subnet: 10.9.0.0/24
